import type { Problem } from "../frontend/src/types/problem";

export const sortingProblems: Problem[] = [
  {
    id: "srt-001",
    slug: "bubble-sort",
    title: "Implement Bubble Sort",
    topic: "Sorting",
    difficulty: "Easy",
    tags: ["sorting", "bubble-sort"],
    statement: "Given an array, sort it in ascending order using the bubble sort algorithm and print the result.",
    inputFormat: "First line: n.\nSecond line: n space-separated integers.",
    outputFormat: "n space-separated integers, sorted ascending.",
    constraints: ["1 <= n <= 2000"],
    examples: [{ input: "5\n5 1 4 2 8", output: "1 2 4 5 8" }],
    hiddenTests: [
      { input: "1\n1", output: "1" },
      { input: "4\n4 3 2 1", output: "1 2 3 4" },
      { input: "5\n1 1 1 1 1", output: "1 1 1 1 1" },
      { input: "6\n-3 5 -1 0 2 -2", output: "-3 -2 -1 0 2 5" },
    ],
    starterCode:
      "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    vector<long long> a(n);\n    for (int i = 0; i < n; i++) cin >> a[i];\n\n    // TODO: implement bubble sort (repeated adjacent swaps) in place\n\n    for (int i = 0; i < n; i++) cout << a[i] << (i + 1 < n ? ' ' : '\\n');\n    return 0;\n}\n",
    hints: [
      "Repeatedly walk through the array, swapping adjacent elements that are out of order.",
      "After each full pass, the largest unsorted element 'bubbles' to its correct position at the end.",
      "You can stop early if a full pass makes no swaps.",
    ],
    timeLimitMs: 1000,
    memoryLimitMb: 256,
  },
  {
    id: "srt-002",
    slug: "merge-sort",
    title: "Implement Merge Sort",
    topic: "Sorting",
    difficulty: "Medium",
    tags: ["sorting", "merge-sort", "divide-and-conquer"],
    statement: "Given an array, sort it in ascending order using merge sort (O(n log n)) and print the result.",
    inputFormat: "First line: n.\nSecond line: n space-separated integers.",
    outputFormat: "n space-separated integers, sorted ascending.",
    constraints: ["1 <= n <= 10^5"],
    examples: [{ input: "6\n38 27 43 3 9 82", output: "3 9 27 38 43 82" }],
    hiddenTests: [
      { input: "1\n42", output: "42" },
      { input: "5\n5 4 3 2 1", output: "1 2 3 4 5" },
      { input: "7\n1 1 1 2 2 0 0", output: "0 0 1 1 1 2 2" },
      { input: "4\n-5 3 -2 8", output: "-5 -2 3 8" },
    ],
    starterCode:
      "#include <bits/stdc++.h>\nusing namespace std;\n\nvoid mergeSort(vector<long long>& a, int l, int r) {\n    // TODO: recursively divide [l, r], sort halves, then merge them\n}\n\nint main() {\n    int n;\n    cin >> n;\n    vector<long long> a(n);\n    for (int i = 0; i < n; i++) cin >> a[i];\n\n    mergeSort(a, 0, n - 1);\n\n    for (int i = 0; i < n; i++) cout << a[i] << (i + 1 < n ? ' ' : '\\n');\n    return 0;\n}\n",
    hints: [
      "Base case: a subarray of length <= 1 is already sorted.",
      "Recursively sort the left half [l, mid] and right half [mid+1, r].",
      "Merge the two sorted halves using a temporary buffer, comparing front elements of each half.",
    ],
    timeLimitMs: 1000,
    memoryLimitMb: 256,
  },
  {
    id: "srt-003",
    slug: "quick-sort",
    title: "Implement Quick Sort",
    topic: "Sorting",
    difficulty: "Medium",
    tags: ["sorting", "quick-sort", "divide-and-conquer"],
    statement: "Given an array, sort it in ascending order using quick sort and print the result.",
    inputFormat: "First line: n.\nSecond line: n space-separated integers.",
    outputFormat: "n space-separated integers, sorted ascending.",
    constraints: ["1 <= n <= 10^5"],
    examples: [{ input: "7\n10 7 8 9 1 5 3", output: "1 3 5 7 8 9 10" }],
    hiddenTests: [
      { input: "1\n9", output: "9" },
      { input: "3\n3 3 3", output: "3 3 3" },
      { input: "5\n1 2 3 4 5", output: "1 2 3 4 5" },
      { input: "6\n6 5 4 3 2 1", output: "1 2 3 4 5 6" },
    ],
    starterCode:
      "#include <bits/stdc++.h>\nusing namespace std;\n\nvoid quickSort(vector<long long>& a, int lo, int hi) {\n    // TODO: pick a pivot, partition the range around it, and recurse on both sides\n}\n\nint main() {\n    int n;\n    cin >> n;\n    vector<long long> a(n);\n    for (int i = 0; i < n; i++) cin >> a[i];\n\n    quickSort(a, 0, n - 1);\n\n    for (int i = 0; i < n; i++) cout << a[i] << (i + 1 < n ? ' ' : '\\n');\n    return 0;\n}\n",
    hints: [
      "Choose a pivot (e.g. the last element) and partition so smaller elements end up left of it, larger to the right.",
      "The Lomuto partition scheme uses a single index tracking the boundary of 'elements smaller than pivot'.",
      "Recurse on the subarrays to the left and right of the pivot's final position.",
    ],
    timeLimitMs: 1000,
    memoryLimitMb: 256,
  },
  {
    id: "srt-004",
    slug: "kth-largest-element",
    title: "Kth Largest Element in an Array",
    topic: "Sorting",
    difficulty: "Medium",
    tags: ["sorting", "quickselect", "heap"],
    statement: "Given an array and an integer k, find the k-th largest element (1-indexed, so k=1 is the maximum).",
    inputFormat: "First line: n and k.\nSecond line: n space-separated integers.",
    outputFormat: "A single integer: the k-th largest element.",
    constraints: ["1 <= k <= n <= 10^5"],
    examples: [
      { input: "6 2\n3 2 1 5 6 4", output: "5" },
      { input: "9 4\n3 2 3 1 2 4 5 5 6", output: "4" },
    ],
    hiddenTests: [
      { input: "1 1\n7", output: "7" },
      { input: "5 5\n1 2 3 4 5", output: "1" },
      { input: "5 1\n1 2 3 4 5", output: "5" },
      { input: "6 3\n6 6 6 1 1 1", output: "6" },
    ],
    starterCode:
      "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int n, k;\n    cin >> n >> k;\n    vector<long long> a(n);\n    for (int i = 0; i < n; i++) cin >> a[i];\n\n    // TODO: find the k-th largest element (sorting works, quickselect/heap is more efficient)\n\n    return 0;\n}\n",
    hints: [
      "The simplest correct approach: sort descending and pick index k-1.",
      "For better average performance, use quickselect (partition-based, like quicksort but recurse only one side).",
      "A min-heap of size k is another O(n log k) approach: keep the k largest seen so far.",
    ],
    timeLimitMs: 1000,
    memoryLimitMb: 256,
  },
  {
    id: "srt-005",
    slug: "sort-colors",
    title: "Sort Colors (Dutch National Flag)",
    topic: "Sorting",
    difficulty: "Medium",
    tags: ["sorting", "two-pointers", "dutch-flag"],
    statement:
      "Given an array containing only 0s, 1s, and 2s, sort it in a single pass using O(1) extra space (the Dutch National Flag algorithm).",
    inputFormat: "First line: n.\nSecond line: n space-separated integers, each 0, 1, or 2.",
    outputFormat: "n space-separated integers, sorted ascending.",
    constraints: ["1 <= n <= 10^5"],
    examples: [{ input: "6\n2 0 2 1 1 0", output: "0 0 1 1 2 2" }],
    hiddenTests: [
      { input: "1\n1", output: "1" },
      { input: "3\n0 0 0", output: "0 0 0" },
      { input: "3\n2 2 2", output: "2 2 2" },
      { input: "5\n1 0 2 1 0", output: "0 0 1 1 2" },
    ],
    starterCode:
      "#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    int n;\n    cin >> n;\n    vector<int> a(n);\n    for (int i = 0; i < n; i++) cin >> a[i];\n\n    // TODO: three-pointer partition (low, mid, high) to sort 0s, 1s, 2s in one pass\n\n    for (int i = 0; i < n; i++) cout << a[i] << (i + 1 < n ? ' ' : '\\n');\n    return 0;\n}\n",
    hints: [
      "Maintain three pointers: low (boundary for 0s), mid (current), high (boundary for 2s).",
      "If a[mid] == 0, swap with low and advance both low and mid.",
      "If a[mid] == 2, swap with high and decrement high (don't advance mid yet, since the swapped-in value is unchecked).",
    ],
    timeLimitMs: 1000,
    memoryLimitMb: 256,
  },
];
